### ISSUE TITLE
Notes on Assertions (for adding to the doc)

### ISSUE THREAD

**Issue by metasj** [underlay/underworld#1]
Meta: post a section at the bottom of the doc that's conversational.  "so you want to..." and discussion  

Idea: Some things to add to the doc  
* fuzziness and disambiguation  
* having a dial to turn from very precise to vague  

Idea: we may want restricted fields.   UUIDs: tricky if individuals self-report; they may not be UU.  Perhaps a "UUID4" field should only be created by some supernodes.    

Q: how to combine lots of assertions about one idea into a node?  
TR: Say I post X=1000 w/ no prov, you post X=1400 w/prov, two others post 2500 and 2800 w/ different provs.  How do you find /see all of those assertions?   Say you query "things w/ type country and name Austria".   You'd want all claims of that sort, perhaps to a few depth-levels.  
 --> nodes aren't real, they are just clusters of properties.  (see also: shapefiles)

TR: Short term, what if we build a quick reduce function that looks at all assetions ever made about a topic.  You have a db-layer of assertion-structure that determines what turns up.   

Idea: Be aware of what unique identifiers are, and what properties are idents.   It's incumbent on a [server/query-engine] to track this, to know when two assertions refer to the same thing and can be merged.  

Aside: J-LD has language as first-class context [so all strings know their lang]

**Comment by joeltg** [comment]
Couple things that need to be fixed (noting mostly for myself):
- [x] Assertions need to be objects at the top-level, not arrays, so that they can be signed (the signature needs to be expressed in properties on a top-level object). This means the array that was previously described needs to live in the `@graph: [...]` property of this (potentially signed) top-level object.
- [x] `prov:Entity` objects should have a `prov:value` that references a [named graph](https://json-ld.org/spec/latest/json-ld/#named-graphs) instead of an asserted object directly. This gets messy quickly (lots of nested `@graph`s) but it's important since `prov:Entity` should reference the assertion-as-a-digital-object, which must have an id distinct from the objects within the assertion.
- [ ] `@id`s in JSON-LD can't be `@index` maps, so we need some other way to "append" properties to existing nodes. A weak version of this is just using `http://schema.org/sameAs` or equivalent, but would love a more formal scheme.
